### PR TITLE
f-takeawaypay-activation@0.10.0 - apply rebranding

### PR DESCRIPTION
**Pull request by oleksiishevchukje**
Rebranding "Takeaway Pay" to "Just Eat Pay"

## UI Review Checks

- [x] README and/or UI Documentation has been [created|updated]
- [x] Unit tests have been [created|updated]
- [ ] This code has been checked with regard to [our accessibility standards](http://fozzie.just-eat.com/documentation/general/accessibility/checklist)

## Browsers Tested

- [x] Chrome (latest)
- [ ] Internet Explorer 11
- [ ] Mobile (Please list device/browser – Ideally one iPhone model and one Android)

### List any other browsers that this PR has been tested in:

- [View the Browser Support Checklist](http://fozzie.just-eat.com/documentation/general/browser-support)

### CODE REVIEW

**Review by zlatinivanov-je — DISMISSED** [review]
LGTM, although the change sounds rather renaming, than rebranding

**Comment by oleksiishevchukje** [comment]
Thanks @zlatinivanov-je . Yeah, true. Renaming as part of rebranding 😄

**Review by DamianMullins — DISMISSED** [review]

**Comment by DamianMullins** [comment]
@oleksiishevchukje I think your most recent merge needs fixing up.

**Comment by oleksiishevchukje** [comment]
@DamianMullins Yeah, I will probably just re-open my PR

**Pull request closed without merging**
