### PR TITLE
fozzie-components@v3.5.0 - Parallelise fozzie-components CircleCI build

### PR DESCRIPTION
**Pull request by LTurns**
**Description**
This PR enables build steps to run in parallel using the following CircleCI workflow:

image

This new workflow consists of the following jobs:

**set_up** - restores cache > installs node_modules > saves cache
**build** - builds bundles / storybook > installs WebDriver deps
**unit_tests** - runs unit tests
**linting** - runs linting
**bundlewatch** - runs bundlewatch checks
**component_tests** - runs component tests (Test failures now produce an MP4 as a build artifact)
**accessibility_tests** - runs accessibility tests (Test failures now produce a11y violation .CSV as build artifact)
**slack_reporting** - reports status to web alerts slack channel

image

### CODE REVIEW

**Review by ashleynolan — DISMISSED** [review]
Would be cool to have a demo of how this works, but as long as it's been tested, happy for this to get merged 👍

**Comment by LTurns** [comment]
> Would be cool to have a demo of how this works, but as long as it's been tested, happy for this to get merged 👍

thanks @ashleynolan, sorry it still needs a bit of work actually so I've added the label of WIP for now 😄 Will definitely demo when we get this working well. Have a good weekend! 😃

**Review by ashleynolan — DISMISSED** [review]

**Comment by siggerzz** [comment]
Found a bug with this, will quickly address

**Comment by siggerzz** [comment]
Fixed 🤞🏼

**Review by minrwhite — APPROVED** [review]

**Review by ashleynolan — APPROVED** [review]

**Pull request merged**
