### PR TITLE
f-metadata@v0.4.0 – Changing Braze to be a dynamic import

### PR DESCRIPTION
**Pull request by ashleynolan**
### Changed
- Changing Braze to be a dynamic import (to save on bundle size of `f-metadata`)

### CODE REVIEW

**Comment by ashleynolan** [comment]
@xander-marjoram @chrisjtownsend Would be good to get your thoughts on this. I haven't fully tested it in something like HomeWeb yet, which would need to be done, but would mean we don't bundle in all of Braze when including the `f-metadata` package potentially.

**Comment by DamianMullins** [comment]
@ashleynolan I'm very interested to see if this works, if so I'm guessing we could code split the config for components like f-searchbox, right?

**Review by DamianMullins — DISMISSED** [review]

**Comment by ashleynolan** [comment]
@DamianMullins It doesn't in its current state atm. Mainly as the build step removes the webpack chunk comments and so it then can't find the file when it's imported into HomeWeb.

I think in this case, I'm going to change the build of this bundle to not be packaged up as a library, so that it can be code-split by the consuming package (atm the code-split happened when the package is built and deployed to NPM), and I can't find any info online with respect to how this could work otherwise…

**Comment by DamianMullins** [comment]
@ashleynolan Is the dynamic import working now?

**Comment by ashleynolan** [comment]
@DamianMullins Yep, but only because the babel transpilation gets handled on the consuming application side now, rather than in the component itself.  So you have to tell your build to compile this module – which would be a bit of a nightmare if we had to do it for library components likethe searchbox/header 😞

**Comment by kevinrodrigues** [comment]
@ashleynolan Is this one OK to close now?

**Comment by ashleynolan** [comment]
@kevinrodrigues Yeh – this went in as part of v1.0.0

**Pull request closed without merging**
