### PR TITLE
f-cookie-banner@v2.2.0 - add tab loop

### PR DESCRIPTION
**Pull request by simonsandersje**
Add a tab loop to keep keyboard users within the modal

## Browsers Tested

- [x] Chrome (latest)

### CODE REVIEW

**Review by DamianMullins — COMMENTED** [review]
As you're using the mega-modal it [should provide you the key-trapping feature automatically when the `open` method is called](https://github.com/justeat/fozzie-components/blob/9159b3a417db7efd9b5fa3577061e0302b2e0a1f/packages/components/molecules/f-mega-modal/src/components/MegaModal.vue#L212-L240). Seems that part isn't triggering for some reason though 🤔

**Comment by simonsandersje** [comment]
@DamianMullins I saw that the tab loop functionality is available in mega modal, but as we don't use the open() method, the keyActions() method isn't called. Refactoring the cookie banner to use the open() method seemed like a lot of work to just get the key-trap functionality

**Comment by kevinrodrigues** [comment]
Hi @DamianMullins @simonsandersje, I've taken a look at this bug ticket (picked it up from Simon to help out). I looked through the cookie banner code and there's quite a bit of logic that depends on the `shouldHideBanner` variable, which means in-order to make this work in the correct way, using `f-mega-modal`'s behaviour, we need to refactor `f-cookie-banner` quite a bit. My suggestion is to allow this PR to go through as a temporary fix for the accessibility issue we have and I will create a ticket so this is corrected, making `f-cookie-banner` use the in-built capabilities that `f-mega-modal` provides. Let me know your thoughts on that?

**Review by kevinrodrigues — APPROVED** [review]

**Review by zlatinivanov-je — APPROVED** [review]

**Comment by zlatinivanov-je** [comment]
> Hi @DamianMullins @simonsandersje, I've taken a look at this bug ticket (picked it up from Simon to help out). I looked through the cookie banner code and there's quite a bit of logic that depends on the `shouldHideBanner` variable, which means in-order to make this work in the correct way, using `f-mega-modal`'s behaviour, we need to refactor `f-cookie-banner` quite a bit. My suggestion is to allow this PR to go through as a temporary fix for the accessibility issue we have and I will create a ticket so this is corrected, making `f-cookie-banner` use the in-built capabilities that `f-mega-modal` provides. Let me know your thoughts on that?

Shall we create an issue or record the described above somewhere so it could be picked up at some point

**Comment by kevinrodrigues** [comment]
> > Hi @DamianMullins @simonsandersje, I've taken a look at this bug ticket (picked it up from Simon to help out). I looked through the cookie banner code and there's quite a bit of logic that depends on the `shouldHideBanner` variable, which means in-order to make this work in the correct way, using `f-mega-modal`'s behaviour, we need to refactor `f-cookie-banner` quite a bit. My suggestion is to allow this PR to go through as a temporary fix for the accessibility issue we have and I will create a ticket so this is corrected, making `f-cookie-banner` use the in-built capabilities that `f-mega-modal` provides. Let me know your thoughts on that?
> 
> Shall we create an issue or record the described above somewhere so it could be picked up at some point

Hi @zlatinivanov-je I have added some info to the original ticket (not sure if we can link internal tickets on a public repo) but can ping that to you :) hope that helps? In terms of the refactor ticket I will create that today and it will be refined by the web team hopefully next week.

**Comment by DamianMullins** [comment]
@kevinrodrigues Yeah that sounds fine, I know we've looked at this functionality in the past (can't remember which component) and it was a little tricky.

**Pull request merged**
