### PR TITLE
storybook@0.14.0 - Remove jest addon from storybook

### PR DESCRIPTION
**Pull request by siggerzz**
- Remove the Storybook Jest addon in favour of allure reporting (still in a branch that's a WIP)

### CODE REVIEW

**Comment by DamianMullins** [comment]
@siggerzz Does this change mean that we no longer need to run `yarn test` before we can start the storybook instance?

**Comment by siggerzz** [comment]
> @siggerzz Does this change mean that we no longer need to run `yarn test` before we can start the storybook instance? 

Correct :)

**Review by kevinrodrigues — DISMISSED** [review]

**Comment by DamianMullins** [comment]
@siggerzz Awesome. In that case, could you also remove the line in the main readme file about having to run that script before starting Storybook, please?

**Review by DamianMullins — APPROVED** [review]

**Review by kevinrodrigues — APPROVED** [review]

**Comment by ashleynolan** [comment]
@siggerzz Can you make sure you mark PRs like this with `#globalconfig` so the Danger checks don't run on sub-packages. Otherwise, it makes it look like we're merging PRs with failing checks.

**Pull request merged**
