### PR TITLE
fozzie-components@1.30.0 - Publish npm packages as part of CI

### PR DESCRIPTION
**Pull request by siggerzz**

### CODE REVIEW

**Comment by DamianMullins** [comment]
@siggerzz will this script try to publish every package?

**Comment by siggerzz** [comment]
@DamianMullins  Currently, yeah. Yet to find an intelligent way to only publish changed packages

**Comment by DamianMullins** [comment]
OK, so I imagine the `npm publish` task will fail, currently, for any packages with versions already published.

**Comment by siggerzz** [comment]
@DamianMullins I usually publish at the root level on my machine and it works fine. From what I can tell, whilst it attempts to publish all packages, it'll skip any that're already up-to-date 👍

**Comment by DamianMullins** [comment]
@siggerzz Nice, I'll have to try that next time I publish a package.

**Review by ashleynolan — APPROVED** [review]
LGTM – out of interest, where does it get the auth token? Is that a key set in Circle's config?

**Comment by siggerzz** [comment]
@ashleynolan Yep, it's in the project config within CircleCI. Currently it's using an npm token that's linked to my account, so it'd be good to create a 'CircleCI' account for NPM and add it to org, that way it doesn't look like I'm the only one publishing packages 😁 .

As it's picked up via env var, we can merge this ticket as is though and then change the token after 👍

**Review by DamianMullins — APPROVED** [review]

**Pull request merged**
