### PR TITLE
f-vue-icons@v2.0.1 - Question mark icon filename casing.

### PR DESCRIPTION
**Pull request by DamianMullins**
### Fixed
- Question mark icon filename casing.

### CODE REVIEW

**Review by simonsandersje — APPROVED** [review]

**Comment by dandel10n** [comment]
Did you rename these files manually? They were generated as part of the build, right?

**Review by FayeCarter — APPROVED** [review]

**Comment by DamianMullins** [comment]
@dandel10n I [renamed the file in f-icons from "questionmark" to "question-mark"](https://github.com/justeat/f-icons/pull/85/files#diff-38c908fb77d7cc7b2eb5642a88c01b04dee4ff9958ab0e46de21bafe088c0547) and this caused the f-vue-icons build script to change the file name to "QuestionMarkIcon" instead of "QuestionmarkIcon". However, with Git, you have to manually update filename case changes by using the `got mv` command i.e. `git mv icons/QuestionmarkIcon.js icons/QuestionMarkIcon.js`.

**Comment by dandel10n** [comment]
> @dandel10n I [renamed the file in f-icons from "questionmark" to "question-mark"](https://github.com/justeat/f-icons/pull/85/files#diff-38c908fb77d7cc7b2eb5642a88c01b04dee4ff9958ab0e46de21bafe088c0547) and this caused the f-vue-icons build script to change the file name to "QuestionMarkIcon" instead of "QuestionmarkIcon". However, with Git, you have to manually update filename case changes by using the `got mv` command i.e. `git mv icons/QuestionmarkIcon.js icons/QuestionMarkIcon.js`.

What I am thinking about is if next build will rewrite the name back again?

**Comment by DamianMullins** [comment]
It shouldn't do as long you have run `yarn install` to get the latest packages. Also, the casing change is a manual thing.

**Pull request merged**
