### PR TITLE
f-header@2.0.0-beta.37 - Changing the saved cards' URL to avoid an unnecessary redirects.

### PR DESCRIPTION
**Pull request by SachaZvetelman**
v2.0.0-beta.37
------------------------------
*Feb 11, 2020*

### Changed
- Saved cards' URL to avoid an unnecessary redirect.

### CODE REVIEW

**Review by kevinrodrigues — DISMISSED** [review]

**Review by simonsandersje — DISMISSED** [review]

**Comment by ashleynolan** [comment]
@SachaZvetelman Can you rename the commit and the title to be `f-header@2.0.0-beta.35`? Just makes it clear what it relates to

**Comment by SachaZvetelman** [comment]
@ashleynolan, can certainly do that.

On a similar note, I think this strategy of including versions in commits has a major downside. If someone starts a new PR before mine gets merged, they will also name it `f-header@2.0.0-beta.35`, causing me to have to rename all my commits and my branch. Any opinions on this?

**Comment by ashleynolan** [comment]
@SachaZvetelman I think it's just a case of whoever's PR gets merged first, then the next PR will need to update their version if they're also using the same version number.

They would need to update their `package.json` version as well anyway (as otherwise they can't release their package), so there's no way around having to update a PR if another one get's merged first. The only solution to this would be to somehow automate the version number change post-merge, but not sure if that's possible.

Appreciate it's not ideal though – we don't seem to hit that use-case a whole lot at least as our review/merge cycle seems to be much shorter for UI components than on something like HomeWeb.

**Comment by SachaZvetelman** [comment]
@ashleynolan, agree it's not a big deal, but probably something a bit annoying. Updating `package.json` and the `CHANGELOG.md` is quite simple. Starting to edit past commits not so much, in general.

But again, not a big deal at this point.

**Comment by ashleynolan** [comment]
@SachaZvetelman For reference – `git rebase -i HEAD~2` is the best method I've found for renaming commits (where `2` is the number of commits to change).

That then lets you rename commit msgs really quickly (as long as you have your default cmd line git editor set to VSCode or something that isn't VIM 😄). After renaming, just force-push to your branch and should all be sorted.

**Review by ashleynolan — DISMISSED** [review]

**Review by kevinrodrigues — APPROVED** [review]

**Review by simonsandersje — APPROVED** [review]

**Pull request merged**
