### PR TITLE
#trivial - Reduce bundlewatch maxsize & target umd js files.

### PR DESCRIPTION
**Pull request by kevinrodrigues**
Noticed my [PR](https://github.com/justeat/fozzie-components/pull/651) is breaking in CI this will target the umd files. Have reduced the maxsize so the umd files do not exceed massively.

### Changes
- Bundle watch maxSize value to `100kb` & target files `umd.min.js`.

### CODE REVIEW

**Review by DamianMullins — DISMISSED** [review]

**Review by DamianMullins — DISMISSED** [review]

**Review by matthewhardern — DISMISSED** [review]

**Comment by xander-marjoram** [comment]
Looks like you may need to add some more exclusions to the bundlewatch config file

**Comment by kevinrodrigues** [comment]
> Looks like you may need to add some more exclusions to the bundlewatch config file

> Looks like you may need to add some more exclusions to the bundlewatch config file

Ill pick this up on monday as ill be back in the web team then. Need to look into the patterns we need.

**Comment by DamianMullins** [comment]
Looks like the oidc package is failing now, but as it bundles to UMD you should be able to [update the generated filename to include the `umd` part](https://github.com/justeat/fozzie-components/blob/9e6bfd1c38d26b636be89ca10412f9474b0c9d72/packages/services/f-consumer-oidc/webpack.config.js#L21).

**Comment by kevinrodrigues** [comment]
> Looks like the oidc package is failing now, but as it bundles to UMD you should be able to [update the generated filename to include the `umd` part](https://github.com/justeat/fozzie-components/blob/9e6bfd1c38d26b636be89ca10412f9474b0c9d72/packages/services/f-consumer-oidc/webpack.config.js#L21).

Yup I added this locally earlier & works ok for this package. The issue is that if it's added then other umd files fail the 100kb limit now. 😄

**Pull request closed without merging**
