### PR TITLE
f-user-message@0.1.1 Fix package registry reference

### PR DESCRIPTION
**Pull request by zlatinivanov-je**
_Removed a reference in `yarn.lock` file to private npm registry_

---

## UI Review Checks

- [x] README and/or UI Documentation has been [created|updated]
- [x] Unit tests have been [created|updated]
- [ ] This code has been checked with regard to [our accessibility standards](http://fozzie.just-eat.com/documentation/general/accessibility/checklist)

## Browsers Tested

- [x] Chrome (latest)
- [ ] Internet Explorer 11
- [ ] Mobile (Please list device/browser – Ideally one iPhone model and one Android)

### List any other browsers that this PR has been tested in:

- [View the Browser Support Checklist](http://fozzie.just-eat.com/documentation/general/browser-support)

### CODE REVIEW

**Review by simonsandersje — APPROVED** [review]

**Comment by DamianMullins** [comment]
@zlatinivanov-je The same fix has just gone into @xander-marjoram's PR #156

**Comment by zlatinivanov-je** [comment]
@DamianMullins would he be publishing this component in that case? I'll be happy to close if that is the case.

**Comment by zlatinivanov-je** [comment]
Closing as this is covered by #156

**Comment by xander-marjoram** [comment]
~@zlatinivanov-je I've published the latest f-services but I suspect you're right, that probably won't help you at the moment. If you merge master into this PR I'll happily approve it.~

The `yarn.lock` lives outside the packages so this should be okay.

**Pull request closed without merging**
