### PR TITLE
#trivial Incorporated Page.withQuery into a param for Page.load

### PR DESCRIPTION
**Pull request by dbernar1**
Simplifies loading a page with the correct config. Removes need for instance data in Page objects.

Old way:
```
button = new Button();
button.withQuery('knob-Button Type', 'primary');
button.withQuery('knob-Button Size', 'medium');
button.load();
```
New way:
```
button.load({
    'Button Type': 'primary',
    'Button Size': 'medium',
});
```

### CODE REVIEW

**Review by zlatinivanov-je — APPROVED** [review]
Maybe consider breaking it down to separate components, even if we have two approaches during the transition to make it easier to review and reduce risk on missing something.

**Comment by ashleynolan** [comment]
@dbernar1 Is this PR still needed? If so, can you resolve the conflicts (or close it if not)

**Comment by dbernar1** [comment]
I'm not sure whether a refactoring is ever needed, but I think the code is better with this change.

I may make the update when I grab a chance, but I'm not sure when I will have the time.

Thanks.

**Comment by siggerzz** [comment]
Apologies for letting this PR get stale. We've got a ticket on the backlog to implement this change.

**Pull request closed without merging**
